{% set name = "peewee-migrate" %}
{% set version = "1.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/peewee_migrate-{{ version }}.tar.gz
  sha256: df7979303c7034f0e51ca7c83044462c33309c8fd217080847aea78291d25014

build:
  entry_points:
    - pw_migrate = peewee_migrate.cli:cli
    - pw-migrate = peewee_migrate.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - peewee <4,>=3
    - click 

test:
  imports:
    - peewee_migrate
  commands:
    - pip check
    - pw_migrate --help
    - pw-migrate --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klen/peewee_migrate
  summary: Support for migrations in Peewee ORM
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
